### ISSUE TITLE
Unable to customize theme in Android.

### ISSUE THREAD

**Issue by 97loser** [Jumio/mobile-flutter#1]
I want to create a customization theme in Android but i didn't get any changes in UI.
Please follow below code which i have tried.

    JumioMobileSDK.initNetverify("**675********-24**-**28-*****************", "VU*********HT***************", "US", {
      "enableVerification": true,
      "enableIdentityVerification": true,
      "cameraPosition": "back",
      "documentTypes": ["DRIVER_LICENSE", "PASSPORT", "IDENTITY_CARD", "VISA"],
    }, {
      "disableBlur": true,
      "backgroundColor": "#045192",
     "positiveButtonBackgroundColor":"#045192"
    }
    );

after initilization JumioMobileSDK i have called
JumioMobileSDK.startNetverify(); (onClick of a button)

**Comment by JumioMobileTeam** [comment]
Hi 97loser,
Android Customization is handled natively via a custom theme - https://github.com/Jumio/mobile-flutter/blob/1c0ef41ec265e1235639912f3864df0d5dc365a6/android/src/main/res/values/styles.xml#L4 . You can use the Surface tool -https://jumio.github.io/surface-android/ to customize the SDK to your needs

**Comment by JoseJET** [comment]
I have tried to clone the package and then put the theme code and then the plugin does not build, saying that most of the styles attrs does not exists

**Comment by bratapfelmus** [comment]
Hi @JoseJET, please contact Jumio support about this issue.
