### ISSUE TITLE
Callback not being sent to specified callbackUrl

### ISSUE THREAD

**Issue by brunovsiqueira** [Jumio/mobile-flutter#10]
Hi there.

The callback event is not being sent to the callbackUrl specified when you call initNetverify or initAuthentication. Instead, it is being sent only to the callbackUrl configured at the Jumio Portal. I tried using the example project but it still doesn't works.

URL configured at the Jumio Portal: http://gatekeeper.uat.quickfin.com.br/biometry/callback
​​​​​URL set in Flutter: http://gatekeeper.uat.quickfin.com.br/biometry/callback/2

Both URLs are working. I saw my backend application logs and no request was sent to http://gatekeeper.uat.quickfin.com.br/biometry/callback/2, only to http://gatekeeper.uat.quickfin.com.br/biometry/callback.

Jumio scanReference: c02dfbec-1584-4f68-9e27-5f78dc9d11fc.

**Comment by bratapfelmus** [comment]
Hi @brunovsiqueira there is already a ticket for this issue and it's being handled. 

Just to update here as well, we're currently getting `(targetUrl=https://gatekeeper.uat.quickfin.com.br/biometry/callback]) - org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error: [{"msg":"unknown error","status":"500"}])` on our end, which means the SDK is getting a server error when trying to reach the callbackUrl that was specified.

**Comment by brunovsiqueira** [comment]
Hi @bratapfelmus. The problem is not the fact you guys trying to reach http://gatekeeper.uat.quickfin.com.br/biometry/callback and getting an error. The problem is you guys not trying to reach the callbackUrl I specified at the frontend (http://gatekeeper.uat.quickfin.com.br/biometry/callback/2), only the one specified at the Jumio Portal (http://gatekeeper.uat.quickfin.com.br/biometry/callback). Se the "/2" difference between both.

**Comment by bratapfelmus** [comment]
@brunovsiqueira this issue seems to have been resolved with using `https` callbackURL instead of `http` URL. 

Will close this for now.
