### ISSUE TITLE
Authentication API was deleted

### ISSUE THREAD

**Issue by JoseJET** [Jumio/mobile-flutter#11]
**Describe the bug**
Authentication API was deleted on v 3.8.0 and when I downgrade to v3.8.0-beta1 and I try the authentication an error (A10403) happens.

**To Reproduce**
On v3.8.0 startAuthentication was deleted
On v3.8.0-beta1 start a new authentication and you will always get error (A10403)

**Additional context**

The native android sdk indicates: [error-codes](https://github.com/Jumio/mobile-sdk-android/blob/master/docs/integration_authentication.md#error-codes)
A[x][yyyy] | We have encountered a network communication problem | Retry possible, user decided to cancel
-- | -- | --

But actually jumio was not launched so the user did not cancelled anything

**Comment by bratapfelmus** [comment]
Hello @JoseJET
please contact support at support@jumio.com!

**Comment by bratapfelmus** [comment]
Authentication has been removed for 3.8.0 and following versions.
It is however still available for 3.8.0-beta1 plugin.
