### ISSUE TITLE
Weird camera filter in 3.8.0

### ISSUE THREAD

**Issue by JoseJET** [Jumio/mobile-flutter#12]
**Describe the bug**
In 3.8.0 the camera shows a weird filter when doing a netverify

**Expected behavior**
In previous versions this was not happening

**Screenshots**
![WhatsApp Image 2021-02-08 at 9 27 19 PM (1)](https://user-images.githubusercontent.com/78734414/107929541-11c8d600-6f7a-11eb-8da7-7f660079d66f.jpeg)

**Comment by bratapfelmus** [comment]
Hi @JoseJET, 
the "weird camera filter" is not a bug but expected behavior due to the use of iProov.
