### ISSUE TITLE
Placeholder text during selfie

### ISSUE THREAD

**Issue by stpe** [Jumio/mobile-flutter#13]
**Describe the bug**
During the selfie scan (see screenshot) placeholder text is shown instead of correct English, e.g. `IProov_PromptLivenessAlignFace`

**To Reproduce**
Always reproducible by doing a selfie scan.

**Expected behavior**
Expected correct English to the user may take action.

**Screenshots**
![IMG_3550](https://user-images.githubusercontent.com/152802/110959170-b954e080-834d-11eb-8db2-f738d7f8774b.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS14.4.1
 - Jumio SDK 3.8
 - Flutter SDK Version 1.22.6

**Comment by Dharmendrabisht** [comment]
@stpe , could you confirm if the translated text is correctly assigned to the placeholder parameter? 
<img width="804" alt="Screenshot 2021-03-14 at 8 35 51 PM" src="https://user-images.githubusercontent.com/33782210/111073715-b56bbe80-8505-11eb-8f07-1976bb34a294.png">

**Comment by bratapfelmus** [comment]
Hello @stpe,

as already stated above, please make sure `Localizable-Netverify.strings` file is up to date. 

If you're having trouble with Localization, please check out: 
https://github.com/Jumio/mobile-sdk-ios/blob/master/docs/known_issues.md#language-localization-issues

**Comment by stpe** [comment]
@bratapfelmus @Dharmendrabisht We are using your Flutter SDK, how does this apply then? Where is the location of the `Localizable-Netverify.strings` file?

**Comment by bratapfelmus** [comment]
@stpe (Just generally speaking, the string files are always located in the iOS directory under --> pods --> JumioMobileSDK.JumioMobileSDK-3.x.x --> Localizations.)

However, this is a known bug we're currently working on. It will be fixed with the Flutter plugin version 3.9.0, which is planned to be released at the end of this week.

**Comment by bratapfelmus** [comment]
Hi @stpe,

version 3.9.0 is out, this issue should be resolved.
