### ISSUE TITLE
Compilation error with Flutter 2.5.0 and mac M1

### ISSUE THREAD

**Issue by aragonet** [Jumio/mobile-flutter#15]
**Describe the bug**
Can not compile app with latest Flutter version 2.5.0 on a mac M1.

**To Reproduce**
1. flutter create test_jumio
2. Add jumio pacakge to yaml: jumio_mobile_sdk_flutter: ^3.9.2
3. Update ios platform to 10.0
4. flutter run
5. See error

**Expected behavior**
Runs the app.

**Smartphone (please complete the following information):**
 - OS: mac M1
 - Flutter SDK Version: 2.5.0

<details>
<summary>Logs</summary>

```
$ flutter run
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                           1.867ms
Running Xcode build...                                                  
Xcode build done.                                           12,8s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[88195]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x20a437ad8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x115c902b8). One of the two will be used. Which one is undefined.
    objc[88195]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x20a437b28) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x115c90308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
```

</details>

**Comment by bratapfelmus** [comment]
Hi @aragonet

Jumio SDK doesn't officially support M1 yet. Building for real devices should work fine, building for simulator is not possible. (We're currently working on a rewrite that will support xcframeworks, arriving with SDK 4.0.0.) 

However, the issue you're describing seems Flutter-specific:
https://stackoverflow.com/questions/65089767/class-amsupporturlconnectiondelegate-is-implemented-in-both
https://github.com/flutter/flutter/issues/75582 

Additionally, what is your `flutter doctor -v` output?

**Comment by bratapfelmus** [comment]
Hello @aragonet  
I see. As mentioned above, unfortunately it is currently is not possible to run Jumio SDK on the simulator on M1 devices. Building it for an actual device should always work. 

Current ETA for Native 4.0.0 is end of October -- crossplatform plugins will be updated as soon as possible after the native release is out.

**Comment by aragonet** [comment]
Ok! Thank you very much
