### ISSUE TITLE
Package dont support null safety

### ISSUE THREAD

**Issue by Magadya** [Jumio/mobile-flutter#17]
**Describe the bug**
Problem run flutter.  Package works like not null safety.
Gradle is 4.1.2 , multiDexEnabled and other setting for android is ok.
**Additional context**
<details>
<summary>Flutter doctor</summary>
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-x64, locale en-BY)
    • Flutter version 2.5.3 at /Users/velmie/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (10 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/velmie/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • M2006C3LG (mobile) • 8H6DQCO7AAIRGIEI • android-arm    • Android 10 (API 29)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
</details>
<details>
<summary>LOGS</summary>

```
[        ] Error: Cannot run with sound null safety, because the following dependencies
[        ] don't support null safety:
[        ]  - package:jumio_mobile_sdk_flutter
[        ] For solutions, see https://dart.dev/go/unsound-null-safety
[+12199 ms] > Task :app:compileFlutterBuildDev01Debug FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/velmie/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDev01Debug'.
[        ] > Process 'command '/Users/velmie/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 17s
[ +389 ms] Exception: Gradle task assembleDev01Debug failed with exit code 1
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:571:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```
</details>

![image](https://user-images.githubusercontent.com/52001214/138732261-d2645d65-3ad0-4fc2-b7c3-c96090cb9cc2.png)

**Smartphone (please complete the following information):**
Android Xiaomi 
![image](https://user-images.githubusercontent.com/52001214/138732775-7d206cf8-5bb5-47ff-a2b6-80bc22ef0ffd.png)

**Comment by bratapfelmus** [comment]
Flutter plugin has been updated to 4.0.0 with sound null safety, closing this issue.
