### ISSUE TITLE
Do you have plan to update Jumio iOS, Android SDK to 4.0.0

### ISSUE THREAD

**Issue by hoang2109** [Jumio/mobile-flutter#18]
Hi there,

As I see currently jumio flutter 3.9.2 is using jumio iOS SDK 3.9.1 and Android SDK 3.9.2 which are out of date. There is newest version for iOS and Android SDK. Do you have any plan to update using sdk 4.0.0? If have let me know when?

Thanks!

**Comment by JumioMobileTeam** [comment]
Hello @hoang2109, 

yes, the update to version 4.0.0 for the Flutter plugin is in the works right now!
Please keep an eye on this repository if you're interested.
