### ISSUE TITLE
How to use set initNetVerify params in new version?

### ISSUE THREAD

**Issue by anas-iqbal** [Jumio/mobile-flutter#19]
Hello team,

In previous version jumio sdk flutter had a initNetVerifyMethod where I was able to set configurations like cameraPosition, callcallbackUrl and other relevant fields, but these method is not recognized in this 4.0.0 version. I also couldn't find any replacement of it in docs can u please help. Below is the method I am referring to.

`  .initNetverify(
            Constant.JUMIO_API_TOKEN,
            Constant.JUMIO_API_SECRET,
            Constant.JUMIO_DATA_CENTER, {
      'enableVerification': true,
      'callbackUrl': ,
      'enableIdentityVerification':,
      // 'preselectedCountry': '',
      'preselectedCountry': ,
      'customerInternalReference':
,
      'userReference': '',
      'sendDebugInfoToJumio':,
      'dataExtractionOnMobileOnly':,
      'cameraPosition': 'back',
    }, {
      'disableBlur':,
      'backgroundColor': '',
    });`

**Comment by bratapfelmus** [comment]
Hello @anas-iqbal, 
as of SDK 4.0.0, all of this information is already included in the `AUTHORIZATION_TOKEN` used to initialize the SDK and has to be specified when requesting that token from the API. 

Please refer to our API guide for detailed information, specifically: https://github.com/Jumio/implementation-guides-develop/blob/master/api-guide/api_guide.md#request-body 
Please also note that customization (e.g. setting backgroundColor) is not yet available for the Flutter plugin.

**Comment by anas-iqbal** [comment]
Hello @bratapfelmus I understand that we have the option to give token and data center in the new version as well, but what about the other options like callback url and other stuff? it's not available in the new version of Jumio, the code I showed above is the working code of jumio flutter sdk old version.

Also the link you shared seems to be broken.

**Comment by bratapfelmus** [comment]
Hello @anas-iqbal, 
not just token and datacenter --> all parameters like callback, userReference, country, document type, etc... have to be set beforehand during the API request call. All of this information (callback, userReference, etc...) are now _already included_ in the sdk authorization token. It is not necessary to specify them in Dart using the `Jumio.init` method any longer.

Please have a closer look at the documentation section I shared above.

**Comment by bratapfelmus** [comment]
No further feedback, closing this issue.
