### ISSUE TITLE
Integration of jumio plugin in flutter project returns exception about an expected argument

### ISSUE THREAD

**Issue by Rhemi7** [Jumio/mobile-flutter#2]
Bug Description
After following the steps to integrate the jumio plugin into the flutter project, when I run build, the build fails with an exception about expecting an argument in the plugin's native code folder.

1. Go to pubspec.yaml and add the jumio sdk package version 3.7.1 and get dependencies
2. open the AndroidManifest file and change allowBackup to false
3. In the app level build.gradle, compileSDKVersion is 29 and buildToolsVersion is 29.0.3
4. in defaultConfig, multiDexEnabled is set to true and the minimum SDK version is 19
5. In the android level builg.gradle, the androidBuildVersion is set to the latest version 4.0.1
6. the gradle/wrapper/gradle-wrapper.properties and update gradle wrapper to 6.1.1
7. After the whole set up, run the flutter project
8. The exception is then returned

Before the integration of the plugin, the project ran as expected after the integration I expected that the build will run successfully so as to be sure that the plugin has been integrated successfully but it failed with an exception.

 - Google Pixel 3a API 21
 - Android 5.0
 - Flutter 1.20.2

**Additional context**
In the app level build.gradle, If minSDKVersion is added and set to 19 in the android curly braces, it returns an exception referring to minSDKVersion argument.

Exception
`C:\Users\Adele Fatai\AppData\Local\Programs\Flutter\.pub-cache\hosted\pub.dartlang.org\jumio_mobile_sdk_flutter-3.7.1\android\src\main\kotlin\com\jumio\jumiomobilesdk\AuthenticationModule.kt: (121, 48): Expecting an argument

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jumio_mobile_sdk_flutter:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`
![Screenshot (376)](https://user-images.githubusercontent.com/54381642/92744998-df3b0180-f379-11ea-8e7f-0308666493c8.png)

**Comment by JumioMobileTeam** [comment]
Hi @Rhemi7 ,
Thank you for your detailed request.
We just noticed that there is a redundant comma "," which most probably leads to the error as the map expects an additional argument here - https://github.com/Jumio/mobile-flutter/blob/1c0ef41ec265e1235639912f3864df0d5dc365a6/android/src/main/kotlin/com/jumio/jumiomobilesdk/AuthenticationModule.kt#L121.
Strangely we don't receive that build error on running the "example" project from this repo. Can you confirm that?

**Comment by Rhemi7** [comment]
Hello @JumioMobileTeam ,
Thanks for the suggestion.
Removing the comma "," worked and now everything works as expected

**Comment by nickolight** [comment]
> Hi @Rhemi7 ,
> Thank you for your detailed request.
> We just noticed that there is a redundant comma "," which most probably leads to the error as the map expects an additional argument here -
> 
> https://github.com/Jumio/mobile-flutter/blob/1c0ef41ec265e1235639912f3864df0d5dc365a6/android/src/main/kotlin/com/jumio/jumiomobilesdk/AuthenticationModule.kt#L121
> 
> .
> Strangely we don't receive that build error on running the "example" project from this repo. Can you confirm that?
> Could you check if removing that comma at the end also resolves the issue on your side?

It worked for me too
