### ISSUE TITLE
Connection error (Error code A10404)

### ISSUE THREAD

**Issue by seantcam** [Jumio/mobile-flutter#21]
Hi there,
I tried to implement the Jumio with my flutter app, following the instruction, but always got the error info as below:

"Connection error, we have encountered a network communication problem(A10404)"

Did I miss something?

Smartphone: 
 - Device: Iphone 7 plus
 - OS: iOS 15
 - Flutter SDK Version: 2.8.1

**Comment by bratapfelmus** [comment]
Hello @seantcam, 
A10404 indicates a network communication problem, usually due to an http error. 

Which version of the Jumio Flutter plugin are you using? 4.0.0? 
Could you share the steps you took that led to you getting this error?

**Comment by seantcam** [comment]
> Hello @seantcam, A10404 indicates a network communication problem, usually due to an http error.
> 
> Which version of the Jumio Flutter plugin are you using? 4.0.0? Could you share the steps you took that led to you getting this error?

Hello @bratapfelmus,
SDK version is 4.0.0. 
I created verification from user portal and parse token from web url, put the token into sample app and got this error.

**Comment by bratapfelmus** [comment]
Hello @seantcam 
since you already have portal access, the easiest way to resolve this issue would be to contact Jumio support.
