### ISSUE TITLE
Issues with jumio_mobile_sdk_flutter 3.9.2. Doesn't work in release(production) mode

### ISSUE THREAD

**Issue by iosmakerov** [Jumio/mobile-flutter#24]
**Describe the bug**

Android:
Works correctly in debug mode. In release mode, the SDK is launched from the country selection screen, but the list is empty and it is not possible to select a country.

iOS:
Works correctly in debug and release mode, but does not work if you upload the application to TestFlight and then install it on the device, an error occurs when starting the SDK: "PlatformException(0, The operation couldn't be completed. JumioCore is expected to be of version 3.9.1, null, null)".

**To Reproduce**
1) Install sdk: jumio_mobile_sdk_flutter: ^3.9.2
2) start sdk
await JumioMobileSDK.initNetverify("***", "***", "US", {
        "enableVerification": true,
        "enableIdentityVerification": true,
        "userReference": userId,
        "customerInternalReference": "paxum",
        "cameraPosition": "back",
        "preselectedDocumentVariant": "plastic",
        "documentTypes": ["DRIVER_LICENSE", "PASSPORT", "IDENTITY_CARD"]
      });
final result = await JumioMobileSDK.startNetverify();

**Smartphone (please complete the following information):**

This behavior is observed on all iOS and Android devices

flutter doctor:
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.5 20G527 darwin-x64, locale ru-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by bratapfelmus** [comment]
Hello @iosmakerov 
please see 
--> https://github.com/Jumio/mobile-flutter#empty-country-list-for-android-release-build
--> https://github.com/Jumio/mobile-sdk-ios/blob/master/docs/known_issues.md#sdk-version-not-compatible-after-xcode-13-update 

If neither one solves the issues you experience, please contact Jumio support.

**Comment by iosmakerov** [comment]
Hello @bratapfelmus 
iOS build problem solved, thanks.

But on Android, the problem with an empty list of countries persists. Although android.permission.INTERNET permission added in AndroidManifest.xml file

**Comment by iosmakerov** [comment]
[project]/android/app/src/main/AndroidManifest.xml :

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.paxum">
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.HIGH_SAMPLING_RATE_SENSORS"/>
  
  <application android:name=".Application" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:allowBackup="false">
    <activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="FLUTTER_NOTIFICATION_CLICK"/>
        <category android:name="android.intent.category.DEFAULT"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data
            android:scheme="pax"
            android:host="deeplink.flutter.dev" />
      </intent-filter>
    </activity>
    <meta-data
        android:name="com.google.firebase.messaging.default_notification_channel_id"
        android:value="@string/notification_channel_id" />
    
    <provider android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider" android:authorities="${applicationId}.flutter_downloader.provider" android:exported="false" android:grantUriPermissions="true">
      <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths"/>
    </provider>
    <meta-data android:name="flutterEmbedding" android:value="2"/>
  </application>
</manifest>`

**Comment by bratapfelmus** [comment]
Hello @iosmakerov 
please contact Jumio support --> https://github.com/Jumio/mobile-flutter#contact
