### ISSUE TITLE
upgrade gnustl to libc++ in the future?

### ISSUE THREAD

**Issue by akeopa** [Jumio/mobile-flutter#25]
I see that the version 4.0.0 of jumio_mobile_sdk_flutter includes libgnustl_shared.so, why does it need to include gnustl, is there any plan to upgrade gnustl to libc++ in the future?

**Comment by bratapfelmus** [comment]
Hello @akeopa 
yes, there will be a switch to libc++ in upcoming versions.

**Comment by akeopa** [comment]
Hi, @bratapfelmus 
Does 4.1.0 include libc++.so?

**Comment by bratapfelmus** [comment]
Hello @akeopa no, it doesn't. 
Please keep an eye on our Android release information for information on this change: 
--> https://github.com/Jumio/mobile-sdk-android/blob/master/docs/changelog.md 
--> https://github.com/Jumio/mobile-sdk-android/blob/master/docs/transition_guide.md

**Comment by akeopa** [comment]
Thx
