### ISSUE TITLE
cannot extract EventResult details after sdk

### ISSUE THREAD

**Issue by gowin8** [Jumio/mobile-flutter#27]
**Describe the bug**
1. It just returns result like {id,credentials}, but EventResult as per document is expected. I want to ask if I started the sdk with some parameters missing. 
By the way, we are using Workflow 3. 

2. How to set the localization? seems it now follow the mobile system localization, but not the localization in our app.

**Comment by bratapfelmus** [comment]
Hello @gowin8

1. Please contact Jumio support with as many details as possible. (SDK plugin version, expected result, actual result, etc...) --> https://github.com/Jumio/mobile-flutter#support
2.  Generally speaking, Jumio SDK language will always mirror overall device language, see also --> https://github.com/Jumio/mobile-sdk-ios/blob/master/docs/integration_faq.md#language-localization

**Comment by gowin8** [comment]
@bratapfelmus  Thank you and the problem is solved.

**Comment by vladyslavmunin** [comment]
@gowin8 how did you solve the problem. I faced with the same issue (1)

**Comment by gowin8** [comment]
@vladyslavmunin  Please directly contact Jumio Support. Since Data Extraction is disabled by default, you may ask them to enable this feature for you.
