### ISSUE TITLE
Issues with jumio_mobile_sdk_flutter 4.0.0:  No type Named 'SDK' in module 'Jumio'

### ISSUE THREAD

**Issue by ebadahmed93** [Jumio/mobile-flutter#28]
**Describe the bug**
I have download jumio4.0.0 source code and open sample app  on flutter 2.5.3 and dart 2.14.4
application is running on android device but on ios is give error in JumioModuleFlutter  class

**To Reproduce**
1. Install flutter 2.5.3 with dart version 2.14.4
2. download Jumio 4.0.0 sourceCode.zip
3.Open Example project  Run on iphone 11 PRO Simulator  (IOS 15.2)

**Expected behavior**
To build application

**Screenshots**
<img width="1440" alt="Screenshot 2022-04-19 at 3 11 18 PM" src="https://user-images.githubusercontent.com/98957067/163981797-5b9f3b4a-3fb8-4dc9-b9c7-a41fbe3377a4.png">

**Smartphone (please complete the following information):**
 - Device: Simulator Iphone 11 pro
 - IOS : 15.2
Logs:

  ** BUILD FAILED **

Xcode's output:
↳
    Command CompileSwiftSources failed with a nonzero exit code
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:5:34: error: no type named 'SDK' in module 'Jumio'
        fileprivate var jumio: Jumio.SDK?
                                     ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:6:36: error: no type named 'ViewController' in module 'Jumio'
        fileprivate var jumioVC: Jumio.ViewController?
                                       ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:5:34: error: no type named 'SDK' in module 'Jumio'
        fileprivate var jumio: Jumio.SDK?
                                     ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:6:36: error: no type named 'ViewController' in module 'Jumio'
        fileprivate var jumioVC: Jumio.ViewController?
                                       ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:57:46: error: no type named 'IDResult' in module 'Jumio'
        private func getIDResult(idResult: Jumio.IDResult) -> [String: Any] {
                                                 ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:84:50: error: no type named 'FaceResult' in module 'Jumio'
        private func getFaceResult(faceResult: Jumio.FaceResult) -> [String: Any] {
                                                     ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:93:37: error: no type named 'DefaultUIDelegate' in module 'Jumio'
    extension JumioModuleFlutter: Jumio.DefaultUIDelegate {
                                        ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:94:27: error: no type named 'SDK' in module 'Jumio'
        func jumio(sdk: Jumio.SDK, finished result: Jumio.Result) {
                              ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:94:55: error: no type named 'Result' in module 'Jumio'
        func jumio(sdk: Jumio.SDK, finished result: Jumio.Result) {
                                                          ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:105:50: error: no type named 'Result' in module 'Jumio'
        private func handleResult(jumioResult: Jumio.Result) {
                                                     ^
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:15:17: error: module 'Jumio' has no member named 'SDK'
            jumio = Jumio.SDK()
                    ^~~~~ ~~~
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:21:34: error: cannot infer contextual base in reference to member 'EU'
                jumio?.dataCenter = .EU
                                    ~^~
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:23:34: error: cannot infer contextual base in reference to member 'SG'
                jumio?.dataCenter = .SG
                                    ~^~
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:25:34: error: cannot infer contextual base in reference to member 'US'
                jumio?.dataCenter = .US
                                    ~^~
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:33:27: error: type of expression is ambiguous without more context
            guard let jumio = jumio else { return }
                              ^~~~~
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:47:29: error: type of expression is ambiguous without more context
            guard let jumioVC = jumioVC else { return }
                                ^~~~~~~
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:49:43: error: cannot infer contextual base in reference to member 'fullScreen'
            jumioVC.modalPresentationStyle = .fullScreen
                                             ~^~~~~~~~~~
    /Users/ebadahmed/Downloads/mobile-flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:134:43: error: type of expression is ambiguous without more context
                guard let error = jumioResult.error else { return }
                                  ~~~~~~~~~~~~^~~~~

**Comment by bratapfelmus** [comment]
Hello @ebadahmed93 
did you make sure to run `flutter pub get` to actually get the SDK plugin first, as mentioned:
here --> https://github.com/Jumio/mobile-flutter/tree/master/example#usage
and here --> https://github.com/Jumio/mobile-flutter#setup 

If yes and this issue still occurs, please contact [Jumio support](https://github.com/Jumio/mobile-flutter#support).

**Comment by ebadahmed93** [comment]
I have already followed the procedures but error remain same.
I will contact jumio support.

**Comment by wangyaboIOS** [comment]
I have the same problem。
Xcode version: 13.2.1
flutter version: 2.10.1

**Comment by ebadahmed93** [comment]
> I have the same problem。 Xcode version: 13.2.1 flutter version: 2.10.1

I am facing this issue only in simulator (tested on IOS 15.2, 14.5)
It is working on real device.
@wangyaboIOS Kindly give it a try with real device and  update if error still occurs.

**Comment by bratapfelmus** [comment]
Hello @wangyaboIOS, @ebadahmed93 
please be aware that as of version 4.0.0, iOS simulator is required to run the latest iOS version.
--> https://github.com/Jumio/mobile-sdk-ios#general-requirements

**Comment by wangyaboIOS** [comment]
Hello @ebadahmed93 
Hello, if you want to run on the emulator, please configure Xcode.
![fix](https://user-images.githubusercontent.com/29478233/168502701-3e127e41-c904-4c44-a2d9-0454ebd627d8.png)

**Comment by wangyaboIOS** [comment]
Hello @ebadahmed93 

if you want to run on the emulator, please configure Xcode.
![fix](https://user-images.githubusercontent.com/29478233/168502844-854e339a-e070-45ac-a892-9b90e19e8119.png)
