### ISSUE TITLE
Selecting country

### ISSUE THREAD

**Issue by nickolight** [Jumio/mobile-flutter#3]
Could you prompt how to start verification from selecting the country screen instead of preselected?

"preselectedCountry": false - doesn't work

**Comment by JumioMobileTeam** [comment]
Verification will always start from the "Scan Options" screen with the country the user is located in by default if no country is preselected specifically. There is no way how to start from the country selection screen directly

**Comment by nickolight** [comment]
I got it. Thank you for your assist.
