### ISSUE TITLE
multi-language & custom translation for v4.1.0 ios

### ISSUE THREAD

**Issue by gowin8** [Jumio/mobile-flutter#30]
**Describe the bug**
Hi Jumio Team, this plugin is awesome! But I encountered problems with language setting.
1. Version 4.1.0 has no multi-language (just English), while v4.0.0 has.
2. I cannot customize the language translations, 
by editing files referenced by Jumio Localiztion [https://github.com/Jumio/mobile-flutter#ios-localization](https://github.com/Jumio/mobile-flutter#ios-localization)
or by creating Localizable.strings file as described here [https://github.com/Jumio/mobile-sdk-ios#language-localization](https://github.com/Jumio/mobile-sdk-ios#language-localization)

**Screenshots**
<img width="689" alt="截屏2022-04-29 17 24 35" src="https://user-images.githubusercontent.com/84638370/165946316-33985344-b1ac-4c72-9801-c904ef7796c6.png">
<img width="868" alt="截屏2022-04-29 20 37 32" src="https://user-images.githubusercontent.com/84638370/165946360-5f07c613-eb47-43c5-894c-cdb7dc7b33cd.png">

**Comment by bratapfelmus** [comment]
Hello @gowin8  
there have been no changes regarding the language localization between 4.0.0 and 4.1.0. 
Please contact Jumio support --> https://github.com/Jumio/mobile-flutter#support

**Comment by JumioMobileTeam** [comment]
Issue has been fixed with release of plugin version 4.2.0
