### ISSUE TITLE
Class 'JumioMobileSdkPlugin' is not abstract and does not implement abstract member

### ISSUE THREAD

**Issue by cipherhammouda** [Jumio/mobile-flutter#33]
on building on android it returns error :
Class 'JumioMobileSdkPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray)

**Comment by bratapfelmus** [comment]
Hello @cipherhammouda 
are you using Flutter 3.0.0 or above? 
If yes, please contact Jumio support --> https://github.com/Jumio/mobile-flutter#support

**Comment by cipherhammouda** [comment]
Just in case the official release for Flutter  >= 3 takes long, you can fix the issue by editing .\android\src\main\kotlin\com\jumio\jumiomobilesdk\JumioMobileSdkPlugin.kt
35: instance.modules.forEach { it.bindToActivity(registrar.activity()) }
to instance.modules.forEach { it.bindToActivity(registrar.activity()!!) }
and 
75:     override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>?, grantResults: IntArray?): Boolean {
to 
    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>, grantResults: IntArray): Boolean {

...
also waiting for their email reply.

**Comment by JumioMobileTeam** [comment]
Issue has been fixed with release of plugin version 4.2.0
