### ISSUE TITLE
randomly appears with data but does not return it

### ISSUE THREAD

**Issue by guixin567** [Jumio/mobile-flutter#34]
**Describe the bug**
at the time of test, found that randomly appears with data but does not return it, print log will find sometimes currentAsyncProcessCallback is empty, so cause a data back to not to come out, help to see what reason is caused, My side is also tracking this issue.

**To Reproduce**
workflowDefinition.key is 10011

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/19410324/185084711-a00832cf-cb77-4451-8a45-99594ae63902.png)

**Smartphone (please complete the following information):**
 - Device: [oppo reno7]
 - OS: [android 12]
 - Flutter SDK Version
 - 3.0.5
 - jumio sdk version
 - 4.2.0

**Comment by BernadetteTh** [comment]
Hello @guixin567 
please contact Jumio support --> https://github.com/Jumio/mobile-flutter#support

**Comment by guixin567** [comment]
> 

ok thank you
