### ISSUE TITLE
Android Netverify Customization

### ISSUE THREAD

**Issue by nickolight** [Jumio/mobile-flutter#4]
The provided link in the docs doesn't work. Could you assist with Android Netverify Customization?

**Comment by JumioMobileTeam** [comment]
Hi @nickolight , sorry for that. The documentation-file was renamed. We'll fix the links.
See https://github.com/Jumio/mobile-sdk-android/blob/master/docs/integration_id-verification-fastfill.md#customization-tool 
The customization is done the native Android way with Themes. You can define create your custom Theme in our Surface Tool https://jumio.github.io/surface-android/ and provide it in here - https://github.com/Jumio/mobile-flutter/blob/master/android/src/main/res/values/styles.xml

**Comment by nickolight** [comment]
Thank you a lot for your assistance. 
Also, I'd like to clarify the field name which allows me to set the color for the focusing lines of the card edges.
All my attempts were unsuccessful. =(
![1603792087022_20201027_115115000_1_1_1](https://user-images.githubusercontent.com/17278021/97286137-cdd78700-184b-11eb-874a-565a2a339941.jpg)

**Comment by JumioMobileTeam** [comment]
Hi @nickolight ,
That's
`		<item name="netverify_scanOverlayDetectedLine">@color/jumio_primary</item>
		<item name="netverify_scanOverlayDetectedLineStroke">@color/jumio_white</item>`

**Comment by nickolight** [comment]
Thanks a lot. 
<item name="netverify_scanOverlayDetectedLine">@color/jumio_primary</item>  - it worked for me. 
About 2nd string - not understand what it helps to customize.

**Comment by bratapfelmus** [comment]
@nickolight 
The line showing the edge detection is actually made up of two colors, the actual "detected line" and the "line stroke" which is drawn around the actual line. 
`<item name="netverify_scanOverlayDetectedLine">` determines the color for the inner part, whereas
`<item name="netverify_scanOverlayDetectedLineStroke">` determines the color for the outer part.

You could try a very dark color for the inner attribute and very light color for the outer one to see the contrast.

**Comment by nickolight** [comment]
@bratapfelmus
I got it. Thanks for the explanation.
