### ISSUE TITLE
iOS Customization

### ISSUE THREAD

**Issue by nickolight** [Jumio/mobile-flutter#5]
Could you assist with iOS customization?
1. '_documentSelectionButtonBackgroundColor_' field doesn't work for me with any color...
2. After I defined '_foregroundColor_' - it changes color a lot of things, that I can't override further. I mean the text color, buttons color, and so on. For example:
        {
          "disableBlur": true,
          "backgroundColor": "#000000",
          "foregroundColor": "#FFFFFF",
        }
I can't set the text color or background color for the button...
![Screenshot 2020-10-27 at 16 59 55](https://user-images.githubusercontent.com/17278021/97319892-f83e3a00-1875-11eb-8b84-123df18621cf.png)

**Comment by nickolight** [comment]
Could you help me? I should describe the issue more in the details?

**Comment by bratapfelmus** [comment]
Sorry for the late response, these buttons can be changed using the parameters
```
positiveButtonBackgroundColor  // button background color
positiveButtonBorderColor          // button border color
positiveButtonTitleColor              // button text color
```
and 
```
negativeButtonBackgroundColor 
negativeButtonBorderColor
negativeButtonTitleColor 
```
respectively.

**Comment by nickolight** [comment]
Hello. Thanks for the clarification.
The point is that these parameters don't work for me. Here is an example of [Map<String, dynamic> customization], and the result respectively:
```
        {
          "disableBlur": true,
          "backgroundColor": "#000000",
          "foregroundColor": "#FFFFFF",
          "positiveButtonBackgroundColor": "#f04747", // red
          "positiveButtonBorderColor": "#4f61a1", // blue
          "positiveButtonTitleColor": "#ffffff", // white
          "negativeButtonBackgroundColor": "#43b00d", // green
          "negativeButtonBorderColor": "#F04747", // red
          "negativeButtonTitleColor": "#fff864", // yellow
        },
```
![IMG_0014](https://user-images.githubusercontent.com/17278021/98643165-3ee06980-2337-11eb-996d-b855fd9ea00e.PNG)

**Comment by bratapfelmus** [comment]
Hi Nikolai,
I just checked and this seems to be an issue on our side. The way it seems to work right now is as follows: 

```
positiveButtonBackgroundColor = foregroundColor
positiveButtonBorderColor = (as it should be)
positiveButtonTitleColor = WHITE 
negativeButtonBackgroundColor = backgroundColor
negativeButtonBorderColor = (as it should be)
negativeButtonTitleColor = foregroundColor
```
We're on it, will let you know when it's fixed.

**Comment by bratapfelmus** [comment]
Hi @nickolight 
any updates? Are you still facing this issue?

**Comment by bratapfelmus** [comment]
Closed because issue has been handled within the 3.8.0 update.
