### ISSUE TITLE
Wrong pop-up message

### ISSUE THREAD

**Issue by mkrisztian95** [Jumio/mobile-flutter#6]
**Describe the bug**
When the user restricts access to the camera, Jumio SDK shows a pop-up with an incorrect message. 

**To Reproduce**
1. Go to 'iPhone Settings'
2. Turn off 'Camera access'
3. Open the app
4. See an error

**Expected behavior**
The app should show a correct pop-up with the app name, or at least without (null).

**Screenshots**
![__2020-11-09__09 41 06](https://user-images.githubusercontent.com/15636314/98928766-d8984a00-24e2-11eb-8a2c-b63baf7f6d30.png)

**Comment by bratapfelmus** [comment]
Hi Chris, 
it seems that the key `CFBundleName` needs to be replace with `CFBundleDisplayName` in the plist file!
