### ISSUE TITLE
Flutter SDK only display UI in English running in iOS

### ISSUE THREAD

**Issue by tcaravanabtg** [Jumio/mobile-flutter#8]
**Describe the bug**
I'm trying to change the localization using Jumio but in iOS no matter which language I choose on system the Jumio interface is always displayed in english using flutter sdk.

**To Reproduce**
1. Download the example project
2. Change your system language to Spanish (I checked the output for Platform.localeName and is "es_ES" in my test)
3. Run the project on a real iOS device
4. Check that interface is always in English, even if I change for any supported language by the iOS SDK

**Expected behavior**
Jumio should at least change the interface language for the supported languages

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.4
 - Flutter SDK Version

**Comment by bratapfelmus** [comment]
Hi @tcaravanabtg 

we've opened a support ticket for this issue, will handle this there.

**Comment by bratapfelmus** [comment]
Localization has been fixed with version 3.8.0.
