### ISSUE TITLE
Android Internationalization Problem

### ISSUE THREAD

**Issue by brunovsiqueira** [Jumio/mobile-flutter#9]
Hi there.

I am having an internationalization problem with Android. When I change my device language preference to PT-BR (Portuguese-Brazil) the Jumio SDK keeps showing String for PT-PT (Portuguese-Portugal). I tried to override this behavior by adding a strings.xml file with new strings (PT-BR) inside my android/app/src/res/values directory but nothing changes. This string are following the names provided in the Android documentation https://github.com/Jumio/mobile-sdk-android/blob/master/sample/JumioMobileSample/src/main/res/values/strings-jumio-sdk.xml.

Having Portuguese-Brazil strings in the Jumio SDK screens is vital for my project. Can you guys please help me with it?

**Comment by bratapfelmus** [comment]
Hi @brunovsiqueira 

here is the full list of languages currently supported by the Jumio SDK: 
https://github.com/Jumio/mobile-sdk-android/blob/master/README.md#language-localization 

Is your res folder containing the Brazilian Portuguese strings.xml file called `values-pt-rBR`? 
This seems to be the appropriate naming convention: https://deepakdroid.medium.com/localize-your-android-application-ffb9ce86989f

**Comment by brunovsiqueira** [comment]
Hi @bratapfelmus. I change the directory name and now it is working properly. Thank you so much for your quick response. You can close this issue now.

**Comment by bratapfelmus** [comment]
@brunovsiqueira glad to hear it! Will add this to our docs as soon as possible, thank you.
